{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "lims.fullname" . }}-secrets
  labels: {{- include "lims.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "lims.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ printf "%s-%s" $.Values.externalSecrets.prefix (lower (replace "_" "-" .)) }}
    {{- end }}
{{- end }}
