apiVersion: v1
kind: Service
metadata:
  name: {{ include "lims.fullname" . }}-backend
  labels: {{- include "lims.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "lims.fullname" . }}-backend"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector: {{- include "lims.componentSelector" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - { name: http, port: 8000, targetPort: http, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lims.fullname" . }}-frontend
  labels: {{- include "lims.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector: {{- include "lims.componentSelector" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      {{- if and (eq (.Values.frontend.service.type | default "ClusterIP") "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
