# Generated by Django 5.2.13 on 2026-05-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_experiment_department'),
        ('orders', '0007_alter_order_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstage',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.equipmenttype'),
        ),
    ]
