# Generated by Django 5.2.13 on 2026-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderstage_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='What the requester needs from this experiment — surfaced to the lab manager during scheduling.'),
        ),
    ]
