# Generated by Django 5.2.13 on 2026-05-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_requirements'),
        ('users', '0005_seed_wafer_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lot_id',
        ),
        migrations.AddField(
            model_name='order',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Registered wafer lot. Pick from the dropdown — picked code is stored as the FK.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.waferlot'),
        ),
    ]
