"""Superuser-only ModelViewSets exposing CRUD over every domain table.

Each viewset reuses an admin-specific serializer (see :mod:`admin_api.serializers`)
and is gated by :class:`monitoring.permissions.IsSystemSuperuser`.
"""
import re

from django.db import transaction
from rest_framework import filters, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.response import Response

from equipments.models import (
    Equipment,
    EquipmentType,
    Experiment,
    ExperimentRequiredEquipment,
)
from monitoring.permissions import IsSystemSuperuser
from orders.models import Order, OrderStage
from scheduling.models import EquipmentBooking
from users.models import FAB, Department, User, WaferLot

from . import serializers as admin_serializers

# Default initial password for accounts created via bulk-create. Long enough
# to pass the production password validator (12+ chars) and contains all four
# character classes most validators look for. Admins can override per call.
DEFAULT_BULK_PASSWORD = 'Lims@2026!Init'

# Hard cap so a single bulk request stays bounded. Comfortable for real
# workflows (3 labs × ~10 members) but won't blow up the database.
MAX_BULK_COUNT = 100


class AdminBaseViewSet(viewsets.ModelViewSet):
    """Shared defaults for every admin viewset: superuser auth + search/order."""

    permission_classes = (IsSystemSuperuser,)
    filter_backends = (filters.SearchFilter, filters.OrderingFilter)


class FABViewSet(AdminBaseViewSet):
    queryset = FAB.objects.all().order_by('fab_name')
    serializer_class = admin_serializers.FABSerializer
    search_fields = ('fab_name',)
    ordering_fields = ('fab_name',)


class DepartmentViewSet(AdminBaseViewSet):
    queryset = Department.objects.select_related('fab').order_by('fab__fab_name', 'name')
    serializer_class = admin_serializers.DepartmentSerializer
    search_fields = ('name', 'fab__fab_name')
    ordering_fields = ('name', 'fab__fab_name')


class WaferLotViewSet(AdminBaseViewSet):
    queryset = WaferLot.objects.select_related('fab').order_by('fab__fab_name', 'code')
    serializer_class = admin_serializers.WaferLotSerializer
    search_fields = ('code', 'notes', 'fab__fab_name')
    ordering_fields = ('code', 'fab__fab_name', 'created_at')


class UserViewSet(AdminBaseViewSet):
    """Manages user accounts. Includes safety rails on destructive operations
    and bulk endpoints used by the admin console to provision groups of
    requesters / lab members / lab managers in one shot.

    Username convention generated by ``bulk_create``:
      * regular_employee  →  ``Emp_001``, ``Emp_002`` …
      * lab_member        →  ``LabMem_<Department>_001``, ``LabMem_<Department>_002`` …
      * lab_manager       →  ``LabMgr_<Department>_001`` …

    The serial restarts at the next free slot for the (role, department) pair,
    so re-running bulk_create after a partial delete fills the gap and never
    collides.
    """

    queryset = User.objects.select_related('department', 'department__fab').order_by('username')
    serializer_class = admin_serializers.UserSerializer
    search_fields = ('username', 'email', 'first_name', 'last_name')
    ordering_fields = ('username', 'role', 'status', 'joined_at')

    def perform_destroy(self, instance):
        if instance == self.request.user:
            raise PermissionDenied('You cannot delete your own account.')
        if instance.role == User.Role.SUPERUSER:
            remaining = User.objects.filter(role=User.Role.SUPERUSER).exclude(pk=instance.pk).count()
            if remaining == 0:
                raise ValidationError('Cannot delete the last remaining superuser.')
        instance.delete()

    # ── Bulk-create ────────────────────────────────────────────────────────

    @action(detail=False, methods=['post'], url_path='bulk-create')
    @transaction.atomic
    def bulk_create(self, request):
        role = request.data.get('role')
        count = request.data.get('count')
        department_id = request.data.get('department')
        password = request.data.get('password') or DEFAULT_BULK_PASSWORD

        valid_roles = {
            User.Role.REGULAR_EMPLOYEE,
            User.Role.LAB_MEMBER,
            User.Role.LAB_MANAGER,
        }
        if role not in valid_roles:
            raise ValidationError({'role': f'Must be one of {sorted(valid_roles)}.'})
        try:
            count = int(count)
        except (TypeError, ValueError):
            raise ValidationError({'count': 'Integer required.'})
        if count < 1 or count > MAX_BULK_COUNT:
            raise ValidationError({'count': f'Must be between 1 and {MAX_BULK_COUNT}.'})
        if len(password) < 8:
            raise ValidationError({'password': 'At least 8 characters.'})

        department = None
        if role in (User.Role.LAB_MEMBER, User.Role.LAB_MANAGER):
            if not department_id:
                raise ValidationError({'department': 'Required for lab roles.'})
            try:
                department = Department.objects.get(pk=department_id)
            except Department.DoesNotExist:
                raise ValidationError({'department': 'Department not found.'})

        prefix = self._username_prefix(role, department)
        usernames = self._next_usernames(prefix, count)

        created = []
        for username in usernames:
            user = User(
                username=username,
                email=f'{username}@lims.local',
                role=role,
                status=User.Status.ACTIVE,
                department=department,
            )
            user.set_password(password)
            user.save()
            created.append(user)

        return Response({
            'created': admin_serializers.UserSerializer(created, many=True).data,
            'count': len(created),
            'password': password,            # echoed once so the admin can hand it out
            'prefix': prefix,
        }, status=201)

    # ── Bulk-delete ────────────────────────────────────────────────────────

    @action(detail=False, methods=['post'], url_path='bulk-delete')
    @transaction.atomic
    def bulk_delete(self, request):
        ids = request.data.get('ids') or []
        if not isinstance(ids, list) or not ids:
            raise ValidationError({'ids': 'Non-empty list of user ids required.'})
        if len(ids) > MAX_BULK_COUNT:
            raise ValidationError({'ids': f'At most {MAX_BULK_COUNT} per call.'})

        skipped = []
        deletable = []
        targets = User.objects.filter(pk__in=ids)
        # Pre-compute remaining superuser count to enforce "never delete the
        # last superuser" across the whole batch.
        will_remove_superuser_ids = {
            t.pk for t in targets if t.role == User.Role.SUPERUSER
        }
        remaining_after_batch = (
            User.objects.filter(role=User.Role.SUPERUSER)
            .exclude(pk__in=will_remove_superuser_ids)
            .count()
        )

        for user in targets:
            if user == request.user:
                skipped.append({'id': str(user.pk), 'reason': 'cannot delete self'})
                continue
            if user.role == User.Role.SUPERUSER and remaining_after_batch == 0:
                skipped.append({
                    'id': str(user.pk),
                    'reason': 'would leave zero remaining superusers',
                })
                continue
            deletable.append(user)

        deleted_ids = [str(u.pk) for u in deletable]
        # Bulk delete to avoid a Python loop over .delete()
        User.objects.filter(pk__in=[u.pk for u in deletable]).delete()

        return Response({
            'deleted_ids': deleted_ids,
            'deleted': len(deleted_ids),
            'skipped': skipped,
        })

    # ── Helpers ────────────────────────────────────────────────────────────

    @staticmethod
    def _username_prefix(role, department):
        if role == User.Role.REGULAR_EMPLOYEE:
            return 'Emp'
        # Strip whitespace from department name for clean usernames
        clean_dept = re.sub(r'\s+', '', department.name) if department else 'Lab'
        return f'LabMem_{clean_dept}' if role == User.Role.LAB_MEMBER else f'LabMgr_{clean_dept}'

    @staticmethod
    def _next_usernames(prefix, count):
        """Return ``count`` usernames extending the existing ``{prefix}_NNN`` series."""
        existing = User.objects.filter(username__startswith=f'{prefix}_').values_list(
            'username', flat=True,
        )
        pattern = re.compile(rf'^{re.escape(prefix)}_(\d+)$')
        max_serial = 0
        for name in existing:
            m = pattern.match(name)
            if m:
                max_serial = max(max_serial, int(m.group(1)))
        return [f'{prefix}_{i:03d}' for i in range(max_serial + 1, max_serial + 1 + count)]


class ExperimentViewSet(AdminBaseViewSet):
    queryset = Experiment.objects.all().order_by('name')
    serializer_class = admin_serializers.ExperimentSerializer
    search_fields = ('name', 'remark')
    ordering_fields = ('name',)


class EquipmentTypeViewSet(AdminBaseViewSet):
    queryset = EquipmentType.objects.all().order_by('name')
    serializer_class = admin_serializers.EquipmentTypeSerializer
    search_fields = ('name',)
    ordering_fields = ('name',)


class EquipmentViewSet(AdminBaseViewSet):
    queryset = Equipment.objects.select_related('equipment_type', 'department').order_by('code')
    serializer_class = admin_serializers.EquipmentSerializer
    search_fields = ('code', 'equipment_type__name')
    ordering_fields = ('code', 'status')


class ExperimentRequiredEquipmentViewSet(AdminBaseViewSet):
    queryset = (
        ExperimentRequiredEquipment.objects
        .select_related('experiment', 'equipment_type')
        .order_by('experiment__name', 'step_order')
    )
    serializer_class = admin_serializers.ExperimentRequiredEquipmentSerializer
    search_fields = ('experiment__name', 'equipment_type__name')
    ordering_fields = ('step_order',)


class OrderViewSet(AdminBaseViewSet):
    queryset = (
        Order.objects
        .select_related('department', 'experiment', 'user', 'assignee')
        .order_by('-created_at')
    )
    serializer_class = admin_serializers.OrderSerializer
    search_fields = ('order_no', 'lot_id', 'user__username', 'experiment__name')
    ordering_fields = ('created_at', 'status', 'is_urgent')


class OrderStageViewSet(AdminBaseViewSet):
    queryset = (
        OrderStage.objects
        .select_related('order', 'department', 'equipment_type', 'equipment', 'assignee')
        .order_by('order__order_no', 'step_order')
    )
    serializer_class = admin_serializers.OrderStageSerializer
    search_fields = ('order__order_no',)
    ordering_fields = ('step_order', 'status')


class EquipmentBookingViewSet(AdminBaseViewSet):
    queryset = (
        EquipmentBooking.objects
        .select_related('order', 'equipment', 'stage')
        .order_by('-started_at')
    )
    serializer_class = admin_serializers.EquipmentBookingSerializer
    search_fields = ('order__order_no', 'equipment__code')
    ordering_fields = ('started_at', 'ended_at')
