# Generated by Django 5.2.13 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
