# Generated by Django 5.2.13 on 2026-05-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_demo_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaferLot',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wafer_lots', to='users.fab')),
            ],
            options={
                'db_table': 'wafer_lot',
                'ordering': ['code'],
            },
        ),
    ]
